### PR TITLE
March 2016 newsletter

### PR DESCRIPTION
**Pull request by pdp7**

### CODE REVIEW

**Comment by pdp7** [comment]
@jadonk  Notes I have so far for March newsletter

**Comment by pdp7** [comment]
@jadonk I've added all the march content to index.html along with images.  Still need to write "from the foundation"
https://pdp7.github.io/newsletter/2016-03/

**Comment by jadonk** [comment]
Any idea why there are conflicts? Can you rebase?

**Comment by pdp7** [comment]
@jadonk I think it was because of https://github.com/jadonk/newsletter/pull/8/commits/c56653fe1282bcca0bce5175752bef89128e0cbd

**Pull request closed without merging**
